### ISSUE TITLE
Grind Universe timer never expires!

### ISSUE THREAD

**Issue by mmosleh** [Dallinger/Griduniverse#193]
I have just used the most updated developer version from Github both for Dallinger and GridUnverse according to the following instruction. When I run the game locally the timer doesn't expire and players are still able to move once time is up! I didn't have this problem with older clone of the Github

Installation instruction:
```
mkvirtualenv test --python /usr/local/bin/python3.6
git clone https://github.com/Dallinger/Dallinger
cd Dallinger/
pip install -r dev-requirements.txt
pip install -e .[data]
pip install -e demos
cd ..
git clone https://github.com/Dallinger/Griduniverse
cd Griduniverse/
pip install -r dev-requirements.txt 
pip install -e.
cd dlgr/griduniverse/
dallinger debug --verbose
```
Error on debug console:

```

❯❯ new recruitment request!
9:48:05 PM web.1    |  2018-09-07 21:48:05,564 35493/4418676040: Subscribed client <dallinger_experiment.experiment.Griduniverse object at 0x1078e0240> to channel griduniverse_ctrl
9:48:05 PM web.1    |  2018-09-07 21:48:05,565 Closing Dallinger DB session at flask request end
9:48:05 PM web.1    |  2018-09-07 21:48:05,566 127.0.0.1 - - [2018-09-07 21:48:05] "POST /launch HTTP/1.1" 200 565 0.179836
9:48:05 PM web.1    |  2018-09-07 21:48:05,569 35493/4421175368: Listening on channel griduniverse_ctrl
9:48:05 PM web.1    |  2018-09-07 21:48:05,667 Spawning food
9:48:06 PM web.1    |  Traceback (most recent call last):
9:48:06 PM web.1    |    File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
9:48:06 PM web.1    |    File "/private/var/folders/mj/yk0p0hnn4mv8cmf16qpmm1zh0000gn/T/tmp63vqhb88/16ec11ff-1772-836f-1b39-90e98a459f4c/experiment.py", line 1483, in game_loop
9:48:06 PM web.1    |      self.grid.spawn_food()
9:48:06 PM web.1    |    File "/private/var/folders/mj/yk0p0hnn4mv8cmf16qpmm1zh0000gn/T/tmp63vqhb88/16ec11ff-1772-836f-1b39-90e98a459f4c/experiment.py", line 789, in spawn_food
9:48:06 PM web.1    |      'position': position,
9:48:06 PM web.1    |  ReferenceError: weakly-referenced object no longer exists
9:48:06 PM web.1    |  2018-09-08T01:48:05Z <Greenlet "Greenlet-0" at 0x10785c748: <bound method Griduniverse.game_loop of <dallinger_experiment.experiment.Griduniverse object at 0x1078e0240>>> failed with ReferenceError
9:48:06 PM web.1    |  2018-09-07 21:48:06,667 Initializing WebSocket
9:48:06 PM web.1    |  2018-09-07 21:48:06,667 Validating WebSocket request
9:48:06 PM web.1    |  2018-09-07 21:48:06,811 Initializing HotAirRecruiter...
9:48:06 PM web.1    |  2018-09-07 21:48:06,829 Closing Dallinger DB session at flask request end
9:48:06 PM web.1    |  2018-09-07 21:48:06,830 127.0.0.1 - - [2018-09-07 21:48:06] "GET /ad?recruiter=hotair&assignmentId=MRMNAD&hitId=A3KJ1U&workerId=W6TDT4&mode=debug HTTP/1.1" 200 3360 0.162803

```

**Comment by alecpm** [comment]
This should be fixed now on master. There was a recent commit that attempted to fix some test isolation issues which prevented the grid state from being properly updated.

**Comment by alecpm** [comment]
@MatthewWilkes ^^^

**Comment by witekdev** [comment]
Works! :smiley_cat:
