### ISSUE TITLE
Keyerror in greenlet

### ISSUE THREAD

**Issue by suchow** [Dallinger/Griduniverse#199]
I was running a GU game and saw the following in the logs:

```
Sep 23 15:21:28 dlgr-b96f5d8e app/web.1:  Traceback (most recent call last): 
Sep 23 15:21:28 dlgr-b96f5d8e app/web.1:    File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run 
Sep 23 15:21:28 dlgr-b96f5d8e app/web.1:    File "/app/experiment.py", line 1234, in send 
Sep 23 15:21:28 dlgr-b96f5d8e app/web.1:      self.dispatch((message)) 
Sep 23 15:21:28 dlgr-b96f5d8e app/web.1:    File "/app/experiment.py", line 1220, in dispatch 
Sep 23 15:21:28 dlgr-b96f5d8e app/web.1:      mapping[msg['type']](msg) 
Sep 23 15:21:28 dlgr-b96f5d8e app/web.1:    File "/app/experiment.py", line 1309, in handle_chat_message 
Sep 23 15:21:28 dlgr-b96f5d8e app/web.1:      msg['server_time'], 
Sep 23 15:21:28 dlgr-b96f5d8e app/web.1:  KeyError: 'server_time' 
```

**Comment by jessesnyder** [comment]
https://github.com/Dallinger/Griduniverse/blob/master/dlgr/griduniverse/experiment.py#L1208 should be:
`msg['server_time'] = time.time()` not `mapping['server_time'] = time.time()`

**Comment by jessesnyder** [comment]
Merged - closing
