### ISSUE TITLE
TypeError in game loop

### ISSUE THREAD

**Issue by suchow** [Dallinger/Griduniverse#201]
```
Sep 23 20:34:31 dlgr-396fef55 app/web.1:  Traceback (most recent call last): 
Sep 23 20:34:31 dlgr-396fef55 app/web.1:    File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run 
Sep 23 20:34:31 dlgr-396fef55 app/web.1:    File "/app/experiment.py", line 1545, in game_loop 
Sep 23 20:34:31 dlgr-396fef55 app/web.1:      del self.grid.food_locations[random.choice(self.grid.food_locations.keys())] 
Sep 23 20:34:31 dlgr-396fef55 app/web.1:    File "/app/.heroku/python/lib/python3.6/random.py", line 259, in choice 
Sep 23 20:34:31 dlgr-396fef55 app/web.1:      return seq[i] 
Sep 23 20:34:31 dlgr-396fef55 app/web.1:  TypeError: 'dict_keys' object does not support indexing 
```

**Comment by jessesnyder** [comment]
@suchow This is fixed in https://github.com/Dallinger/Griduniverse/tree/reliability-and-stats:
https://github.com/Dallinger/Griduniverse/commit/9fbbcede1a9709068cb7bb2ef3bf07b9e268eaf5
