### ISSUE TITLE
Error raised attempting to add non-`working` participant to Grid

### ISSUE THREAD

**Issue by jessesnyder** [Dallinger/Griduniverse#204]
Reported by @MatthewWilkes in Slack channel.

Perhaps participant is `overrecruited`?
```
Sep 21 08:19:58 dlgr-3db88e33 app/web.1: 2018-09-21 15:19:58,461 Found an open network. Adding participant node... 
Sep 21 08:19:58 dlgr-3db88e33 app/web.1: Traceback (most recent call last): 
Sep 21 08:19:58 dlgr-3db88e33 app/web.1:   File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run 
Sep 21 08:19:58 dlgr-3db88e33 app/web.1:   File "/app/experiment.py", line 1270, in send 
Sep 21 08:19:58 dlgr-3db88e33 app/web.1:     self.dispatch((message)) 
Sep 21 08:19:58 dlgr-3db88e33 app/web.1:   File "/app/experiment.py", line 1252, in dispatch 
Sep 21 08:19:58 dlgr-3db88e33 app/web.1:     mapping[msg['type']](msg) 
Sep 21 08:19:58 dlgr-3db88e33 app/web.1:   File "/app/experiment.py", line 1315, in handle_connect 
Sep 21 08:19:58 dlgr-3db88e33 app/web.1:     node = self.create_node(participant, network) 
Sep 21 08:19:58 dlgr-3db88e33 app/web.1:   File "/app/experiment.py", line 1189, in create_node 
Sep 21 08:19:58 dlgr-3db88e33 app/web.1:     network=network, participant=participant 
Sep 21 08:19:58 dlgr-3db88e33 app/web.1:   File "<string>", line 4, in __init__ 
Sep 21 08:19:58 dlgr-3db88e33 app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/state.py", line 417, in _initialize_instance 
Sep 21 08:19:58 dlgr-3db88e33 app/web.1:     manager.dispatch.init_failure(self, args, kwargs) 
Sep 21 08:19:58 dlgr-3db88e33 app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__ 
Sep 21 08:19:58 dlgr-3db88e33 app/web.1:     compat.reraise(exc_type, exc_value, exc_tb) 
Sep 21 08:19:58 dlgr-3db88e33 app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 249, in reraise 
Sep 21 08:19:58 dlgr-3db88e33 app/web.1:     raise value 
Sep 21 08:19:58 dlgr-3db88e33 app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/state.py", line 414, in _initialize_instance 
Sep 21 08:19:58 dlgr-3db88e33 app/web.1:     return manager.original_init(*mixed[1:], **kwargs) 
Sep 21 08:19:58 dlgr-3db88e33 app/web.1:   File "/app/.heroku/src/dallinger/dallinger/models.py", line 665, in __init__ 
Sep 21 08:19:58 dlgr-3db88e33 app/web.1:     .format(participant)) 
Sep 21 08:19:58 dlgr-3db88e33 app/web.1: ValueError: <dallinger.models.Participant object at 0x7f747e7474a8> cannot create a node as they are not working 
Sep 21 08:19:58 dlgr-3db88e33 app/web.1: 2018-09-21T15:19:58Z <Greenlet "Greenlet-0" at 0x7f7462e60448: <bound method Griduniverse.send of <dallinger_experiment.experiment.Griduniverse object at 0x7f747ef31fd0>>('griduniverse_ctrl:{"type":"connect","player_id":")> failed with ValueError 
```

**Comment by cguardia** [comment]
This and related exceptions have been addressed by https://github.com/Dallinger/Griduniverse/pull/217
