### ISSUE TITLE
Error on move event

### ISSUE THREAD

**Issue by jessesnyder** [Dallinger/Griduniverse#205]
Reported by @MatthewWilkes in Slack channel:

```
Sep 21 08:20:15 dlgr-3db88e33 app/web.1: 2018-09-21T15:20:14Z <Greenlet "Greenlet-0" at 0x7f7462e60448: <bound method Griduniverse.send of <dallinger_experiment.experiment.Griduniverse object at 0x7f747ef31fd0>>('griduniverse_ctrl:{"type":"move","player_id":"14")> failed with ValueError 
Sep 21 08:20:15 dlgr-3db88e33 app/web.1: Traceback (most recent call last): 
Sep 21 08:20:15 dlgr-3db88e33 app/web.1:   File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run 
Sep 21 08:20:15 dlgr-3db88e33 app/web.1:   File "/app/experiment.py", line 1272, in send 
Sep 21 08:20:15 dlgr-3db88e33 app/web.1:     self.record_event(message, message['player_id']) 
Sep 21 08:20:15 dlgr-3db88e33 app/web.1:   File "/app/experiment.py", line 1288, in record_event 
Sep 21 08:20:15 dlgr-3db88e33 app/web.1:     info = Event(origin=node, details=details) 
Sep 21 08:20:15 dlgr-3db88e33 app/web.1:   File "<string>", line 4, in __init__ 
Sep 21 08:20:15 dlgr-3db88e33 app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/state.py", line 417, in _initialize_instance 
Sep 21 08:20:15 dlgr-3db88e33 app/web.1:     manager.dispatch.init_failure(self, args, kwargs) 
Sep 21 08:20:15 dlgr-3db88e33 app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__ 
Sep 21 08:20:15 dlgr-3db88e33 app/web.1:     compat.reraise(exc_type, exc_value, exc_tb) 
Sep 21 08:20:15 dlgr-3db88e33 app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 249, in reraise 
Sep 21 08:20:15 dlgr-3db88e33 app/web.1:     raise value 
Sep 21 08:20:15 dlgr-3db88e33 app/web.1:   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/state.py", line 414, in _initialize_instance 
Sep 21 08:20:15 dlgr-3db88e33 app/web.1:     return manager.original_init(*mixed[1:], **kwargs) 
Sep 21 08:20:15 dlgr-3db88e33 app/web.1:   File "/app/models.py", line 16, in __init__ 
Sep 21 08:20:15 dlgr-3db88e33 app/web.1:     super(Event, self).__init__(origin) 
Sep 21 08:20:15 dlgr-3db88e33 app/web.1:   File "<string>", line 6, in __init__ 
Sep 21 08:20:15 dlgr-3db88e33 app/web.1:   File "/app/.heroku/src/dallinger/dallinger/models.py", line 1478, in __init__ 
Sep 21 08:20:15 dlgr-3db88e33 app/web.1:     .format(origin)) 
Sep 21 08:20:15 dlgr-3db88e33 app/web.1: ValueError: Node-8-node cannot create an info as it has failed 
Sep 21 08:20:15 dlgr-3db88e33 app/web.1: 2018-09-21T15:20:15Z <Greenlet "Greenlet-0" at 0x7f7462e60448: <bound method Griduniverse.send of <dallinger_experiment.experiment.Griduniverse object at 0x7f747ef31fd0>>('griduniverse_ctrl:{"type":"move","player_id":"14")> failed with ValueError 
```

**Comment by alecpm** [comment]
I think the simplest solution here is probably just to catch this error in `Griduniverse.record_event` and log the data. Presumably any new `Info` being recorded on a node that's already been marked as failed, is one that was delayed significantly and is not likely to be critical. The alternative would be removing the condition that forces Info creation to fail on failed nodes, and instead marks them as delayed in some manner.
