### ISSUE TITLE
Server-side error on transition

### ISSUE THREAD

**Issue by jessesnyder** [Dallinger/Griduniverse#285]
Traceback:
```
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/private/tmp/dallinger_develop/experiment.py", line 1303, in send
    self.dispatch((message))
  File "/private/tmp/dallinger_develop/experiment.py", line 1291, in dispatch
    mapping[msg["type"]](msg)
  File "/private/tmp/dallinger_develop/experiment.py", line 1618, in handle_item_transition
    item_config=self.item_config[transition["actor_end"]],
KeyError: None
2024-05-21T20:03:39Z <Greenlet at 0x1102c9940: <bound method Griduniverse.send of <dallinger_experiment.experiment.Griduniverse object at 0x10d6e9690>>('griduniverse_ctrl:{"type":"item_transition","play)> failed with KeyError
```

Transition definition in question:
```yaml
  - actor_start: diamond
    actor_end: null
    target_start: stone
    target_end: crown
    visible: always
    last_use: false
    modify_uses:
      - 0
      - 0
```

**Comment by jessesnyder** [comment]
Fixed; closing
